---

dependencies: []

galaxy_info:

  role_name: 'neurodebian'
  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Install packages from the NeuroDebian repository'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.5'

  platforms:

    - name: Debian
      versions:
        - squeeze
        - wheezy
        - jessie

    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - yakkety

  galaxy_tags:
    - science
    - neuroscience
    - education
    - research
    - apt
