---

- name: Manage SMS Gateway service
  hosts: [ 'debops_service_smstools' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.postfix/env
      tags: [ 'role::postfix', 'role::secret', 'role::ferm' ]

    - role: debops.secret
      tags: [ 'role::secret', 'role::postfix' ]
      secret__directories:
        - '{{ postfix__secret__directories }}'

    - role: debops.etc_services
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list:
        - '{{ smstools__etc_services__dependent_list }}'

    - role: debops.rsyslog
      tags: [ 'role::syslog' ]

    - role: debops.tcpwrappers
      tags: [ 'role::tcpwrappers' ]
      tcpwrappers__dependent_allow:
        - '{{ smstools__tcpwrappers__dependent_allow }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ postfix__ferm__dependent_rules }}'
        - '{{ smstools__ferm__dependent_rules }}'

    - role: debops.postfix
      tags: [ 'role::postfix' ]
      postfix__dependent_maincf:
        - role: 'smstools'
          config: '{{ smstools__postfix__dependent_maincf }}'
      postfix__dependent_mastercf:
        - role: 'smstools'
          config: '{{ smstools__postfix__dependent_mastercf }}'

    - role: debops.smstools
      tags: [ 'role::smstools' ]
