---

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save nsswitch local facts
  template:
    src: 'etc/ansible/facts.d/nsswitch.fact.j2'
    dest: '/etc/ansible/facts.d/nsswitch.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: nsswitch__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: nsswitch__register_facts is changed

- name: Generate Name Service Switch configuration
  template:
    src: 'etc/nsswitch.conf.j2'
    dest: '/etc/nsswitch.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: nsswitch__enabled|bool
