---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.unbound default variables [[[
# ====================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# APT packages [[[
# ----------------

# .. envvar:: unbound__base_packages [[[
#
# List of default APT packages to install for Unbound support.
unbound__base_packages: [ 'unbound' ]

                                                                   # ]]]
# .. envvar:: unbound__packages [[[
#
# List of additional APT packages to install with Unbound.
unbound__packages: []
                                                                   # ]]]
                                                                   # ]]]
# Server (main) configuration [[[
# -------------------------------

# These variables can be used to configure main :command:`unbound`
# configuration options. See :ref:`unbound__ref_server` for more details.

# .. envvar:: unbound__default_server [[[
#
# The default Unbound 'server' configuration defined by the role.
unbound__default_server: []

                                                                   # ]]]
# .. envvar:: unbound__server [[[
#
# The Unbound 'server' configuration which should be present on all hosts in
# the Ansible inventory.
unbound__server: []

                                                                   # ]]]
# .. envvar:: unbound__group_server [[[
#
# The Unbound 'server' configuration which should be present on hosts in
# a specific Ansible inventory group.
unbound__group_server: []

                                                                   # ]]]
# .. envvar:: unbound__host_server [[[
#
# The Unbound 'server' configuration which should be present on specific hosts
# in the Ansible inventory.
unbound__host_server: []

                                                                   # ]]]
# .. envvar:: unbound__combined_server [[[
#
# This variable combines the 'server' configuration from other variables and
# passes it to the configuration file template.
unbound__combined_server: '{{ unbound__default_server
                              + unbound__server
                              + unbound__group_server
                              + unbound__host_server }}'
                                                                   # ]]]
                                                                   # ]]]
# Remote control configuration [[[
# --------------------------------

# These variables can be used to configure :command:`unbound-control`
# configuration options. The syntax is the same as the 'server' configuration.
# See :ref:`unbound__ref_server` for more details.

# .. envvar:: unbound__remote_control [[[
#
# The Unbound 'remote-control' configuration which should be present on all
# hosts in the Ansible inventory.
unbound__remote_control: []

                                                                   # ]]]
# .. envvar:: unbound__group_remote_control [[[
#
# The Unbound 'remote-control' configuration which should be present on hosts
# in a specific Ansible inventory group.
unbound__group_remote_control: []

                                                                   # ]]]
# .. envvar:: unbound__host_remote_control [[[
#
# The Unbound 'remote-control' configuration which should be present on
# specific hosts in the Ansible inventory.
unbound__host_remote_control: []

                                                                   # ]]]
# .. envvar:: unbound__combined_remote_control [[[
#
# This variable combines the 'remote-control' configuration from other
# variables and passes it to the configuration file template.
unbound__combined_remote_control: '{{ unbound__remote_control
                                      + unbound__group_remote_control
                                      + unbound__host_remote_control }}'
                                                                   # ]]]
                                                                   # ]]]
# Custom forward/stub DNS zones [[[
# ---------------------------------

# These variables configure custom 'forward' or 'stub' DNS zones served by
# Unbound. See :ref:`unbound__ref_zones` for more details.

# .. envvar:: unbound__zones [[[
#
# List of forward or stub DNS zones which should be defined on all hosts in the
# Ansible inventory.
unbound__zones: []

                                                                   # ]]]
# .. envvar:: unbound__group_zones [[[
#
# List of forward or stub DNS zones which should be defined on hosts in
# specific Ansible inventory group.
unbound__group_zones: []

                                                                   # ]]]
# .. envvar:: unbound__host_zones [[[
#
# List of forward or stub DNS zones which should be defined on specific hosts
# in the Ansible inventory.
unbound__host_zones: []

                                                                   # ]]]
# .. envvar:: unbound__combined_zones [[[
#
# The variable that combines the zone configuration from other variables.
unbound__combined_zones: '{{ unbound__zones
                             + unbound__group_zones
                             + unbound__host_zones }}'

                                                                   # ]]]
# .. envvar:: unbound__parsed_zones [[[
#
# The variable that parses the combined zone configuration and is used in the
# Ansible tasks to manage the DNS zone files.
unbound__parsed_zones: '{{ unbound__combined_zones
                                | parse_kv_items }}'
                                                                   # ]]]
                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: unbound__apt_preferences__dependent_list [[[
#
# Configuration for the :ref:`debops.apt_preferences`.
unbound__apt_preferences__dependent_list:

  - packages:  [ 'unbound', 'unbound-*', 'python-unbound', 'python3-unbound', 'libunbound*' ]
    backports: [ 'wheezy', 'jessie' ]
    reason:    'Feature parity with the next Debian release'
    by_role:   'debops.unbound'

                                                                   # ]]]
# .. envvar:: unbound__etc_services__dependent_list [[[
#
# Configuration for the :ref:`debops.etc_services`.
unbound__etc_services__dependent_list:

  - name: 'unbound-ctrl'
    port: '8953'
    comment: 'Unbound control service'
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
