---

dependencies:
  - role: debops.secret

galaxy_info:

  role_name: 'gitlab_runner'
  author: 'Maciej Delmanowski'
  description: 'Manage GitLab Runner instances'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - development
    - gitlab
    - git
    - docker
    - ssh
    - ci
