---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'netbase'
  author: 'Maciej Delmanowski'
  description: 'Configure local host and network database'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
    - name: FreeBSD
      versions: 12.0
  galaxy_tags:
    - networking
    - hosts
    - system
    - nss
