---

dependencies: []

galaxy_info:

  role_name: 'etc_services'
  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage service definitions in /etc/services'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - networking
    - system
