---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'unbound'
  author: 'Maciej Delmanowski'
  description: 'Install and configure Unbound, local DNS resolver'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.3.0'

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - dns
    - dnssec
