---

dependencies: []

galaxy_info:

  role_name: 'apt_proxy'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage APT proxy configuration'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'

  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
  - apt
  - proxy
  - squid
  - cache
