---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops-contrib.btrfs default variables [[[
# ==========================================

# .. contents:: Sections
#    :local:
#
# .. include:: includes/all.rst


# Required packages [[[
# ---------------------

# .. envvar:: btrfs__base_packages [[[
#
# List of base packages to install.
btrfs__base_packages:
  - 'btrfs-tools'
                                                                   # ]]]
                                                                   # ]]]
# Subvolumes [[[
# --------------

# .. envvar:: btrfs__subvolumes [[[
#
# Dict of BTRFS subvolumes.
btrfs__subvolumes: {}

                                                                   # ]]]
# .. envvar:: btrfs__subvolumes_host_group [[[
#
# See :envvar:`btrfs__subvolumes`.
btrfs__subvolumes_host_group: {}

                                                                   # ]]]
# .. envvar:: btrfs__subvolumes_host [[[
#
# See :envvar:`btrfs__subvolumes`.
btrfs__subvolumes_host: {}
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
