---

# Where to look for OpenVZ GPG key
openvz_gnupg_keyserver: 'hkp://pool.sks-keyservers.net'
openvz_gnupg_key_id: 'A7A1D4B6'

# Notification message about new of updated OpenVZ kernel
openvz_mail_kernel_subject: 'OpenVZ kernel update on {{ ansible_fqdn }}'

openvz_mail_kernel_body: |
  Ansible has updated Linux kernel with OpenVZ support on host {{ ansible_fqdn }}
  You should check status of the host and reboot it when convenient.

  Current kernel: {{ ansible_kernel }}
  Output of apt-get install {{ openvz_kernel }}:
  ---------------------------------------------------------------
  {% for line in openvz_kernel_status.stdout_lines %}
  {{ line }}
  {% endfor %}
  ---------------------------------------------------------------

  GRUB will reboot to kernel from menu item: {{ openvz_grub_default }}
  Output of update-grub:
  ---------------------------------------------------------------
  {% for line in openvz_grub_status.stdout_lines %}
  {{ line }}
  {% endfor %}
  ---------------------------------------------------------------

  Output of vzlist --all:
  ---------------------------------------------------------------
  {% for line in openvz_vzlist_status.stdout_lines %}
  {{ line }}
  {% endfor %}
  ---------------------------------------------------------------


# ---- Salt integration ----

# SaltStack Debian repository GPG key
openvz_template_salt_apt_key_url: 'http://debian.saltstack.com/debian-salt-team-joehealy.gpg.key'

# SaltStack Debian APT repository
openvz_template_salt_upstream_repository: 'deb http://debian.saltstack.com/debian {{ ansible_distribution_release.split("/")[0] }}-saltstack main'
