---

- name: Pre hooks
  include: "{{ lookup('task_src', 'dovecot/pre_main.yml') }}"

- name: Install Dovecot packages
  apt:
    pkg: '{{ item }}'
    state: 'present'
    install_recommends: 'no'
  with_flattened:
    - [ 'dovecot-core' ]
    - [ '{{ "dovecot-imapd" if "imap" in dovecot_protocols else [] }}' ]
    - [ '{{ "dovecot-pop3d" if "pop3" in dovecot_protocols else [] }}' ]
    - [ '{{ "dovecot-lmtpd" if "lmtp" in dovecot_protocols else [] }}' ]
    - [ '{{ "dovecot-mysql" if (("sql" in dovecot_user_accounts) and ("mysql" in dovecot_sql_driver)) else [] }}' ]
    - [ '{{ "dovecot-pgsql" if (("sql" in dovecot_user_accounts) and ("pgsql" in dovecot_sql_driver)) else [] }}' ]
    - [ '{{ "dovecot-managesieved" if "managesieve" in dovecot_protocols else [] }}' ]
  register: dovecot__register_packages
  until: dovecot__register_packages is succeeded

- name: Divert original Dovecot configuration
  command: dpkg-divert --quiet --local
           --divert /etc/dovecot/conf.d/{{ item }}.dpkg-divert
           --rename /etc/dovecot/conf.d/{{ item }}
           creates=/etc/dovecot/conf.d/{{ item }}.dpkg-divert
  with_flattened:
    - [ '10-auth.conf', '10-mail.conf', '10-master.conf', '10-ssl.conf', '15-lda.conf' ]
    - [ '{{ "20-imap.conf" if "imap" in dovecot_protocols else [] }}' ]
    - [ '{{ "20-pop3.conf" if "pop3" in dovecot_protocols else [] }}' ]
    - [ '{{ "20-lmtp.conf" if "lmtp" in dovecot_protocols else [] }}' ]
    - [ '{{ "auth-deny.conf.ext" if "deny" in dovecot_user_accounts else [] }}' ]
    - [ '{{ "auth-system.conf.ext" if "system" in dovecot_user_accounts else [] }}' ]
    - [ '{{ "auth-sql.conf.ext" if "sql" in dovecot_user_accounts else [] }}' ]
    - [ '{{ [ "20-managesieve.conf", "90-sieve.conf", "90-sieve-extprograms.conf" ]
            if "managesieve" in dovecot_protocols else [] }}' ]
  notify: [ 'Restart dovecot' ]

- name: Remove redundant Dovecot configurations
  file:
    dest: '/etc/dovecot/conf.d/{{ item }}'
    state: absent
  with_flattened:
    - [ '{{ "20-imap.conf" if "imap" not in dovecot_protocols else [] }}' ]
    - [ '{{ "20-pop3.conf" if "pop3" not in dovecot_protocols else [] }}' ]
    - [ '{{ "20-lmtp.conf" if "lmtp" not in dovecot_protocols else [] }}' ]
    - [ '{{ [ "20-managesieve.conf", "90-sieve.conf", "90-sieve-extprograms.conf" ]
            if "managesieve" not in dovecot_protocols else [] }}' ]
  notify: [ 'Restart dovecot' ]

- name: Remove diversion of original Dovecot configuration
  command: dpkg-divert --quiet --local --rename --remove /etc/dovecot/conf.d/{{ item }}
           removes=/etc/dovecot/conf.d/{{ item }}.dpkg-divert
  with_flattened:
    - [ '{{ "20-imap.conf" if "imap" not in dovecot_protocols else [] }}' ]
    - [ '{{ "20-pop3.conf" if "pop3" not in dovecot_protocols else [] }}' ]
    - [ '{{ "20-lmtp.conf" if "lmtp" not in dovecot_protocols else [] }}' ]
    - [ '{{ [ "20-managesieve.conf", "90-sieve.conf", "90-sieve-extprograms.conf" ]
            if "managesieve" not in dovecot_protocols else [] }}' ]

- name: Uninstall disabled Dovecot protocols
  apt:
    pkg: '{{ item }}'
    state: 'absent'
  with_flattened:
    - [ '{{ "dovecot-imapd" if "imap" not in dovecot_protocols else [] }}' ]
    - [ '{{ "dovecot-pop3d" if "pop3" not in dovecot_protocols else [] }}' ]
    - [ '{{ "dovecot-lmtpd" if "lmtp" not in dovecot_protocols else [] }}' ]
    - [ '{{ "dovecot-mysql"
        if (("sql" not in dovecot_user_accounts) or ("mysql" not in dovecot_sql_driver)) else [] }}' ]
    - [ '{{ "dovecot-pgsql"
            if (("sql" not in dovecot_user_accounts) or ("pgsql" not in dovecot_sql_driver)) else [] }}' ]
    - [ '{{ "dovecot-managesieved" if "managesieve" not in dovecot_protocols else [] }}' ]
  notify: [ 'Restart dovecot' ]

- name: Generate Dovecot configuration
  template:
    src: '{{ lookup("template_src", "etc/dovecot/conf.d/" + item + ".j2") }}'
    dest: '/etc/dovecot/conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_flattened:
    - [ '10-auth.conf', '10-mail.conf', '10-master.conf', '10-ssl.conf', '15-lda.conf' ]
    - [ '{{ "20-imap.conf" if "imap" in dovecot_protocols else [] }}' ]
    - [ '{{ "20-pop3.conf" if "pop3" in dovecot_protocols else [] }}' ]
    - [ '{{ "20-lmtp.conf" if "lmtp" in dovecot_protocols else [] }}' ]
    - [ '{{ "auth-deny.conf.ext" if "deny" in dovecot_user_accounts else [] }}' ]
    - [ '{{ "auth-system.conf.ext" if "system" in dovecot_user_accounts else [] }}' ]
    - [ '{{ "auth-sql.conf.ext" if "sql" in dovecot_user_accounts else [] }}' ]
    - [ '{{ "auth-passwdfile.conf.ext" if "passwdfile" in dovecot_user_accounts else [] }}' ]
    - [ '{{ [ "20-managesieve.conf", "90-sieve.conf", "90-sieve-extprograms.conf" ]
            if "managesieve" in dovecot_protocols else [] }}' ]
  notify: [ 'Restart dovecot' ]

- name: Generate Dovecot local configuration
  template:
    src: "{{ lookup('template_src', 'etc/dovecot/local.conf.j2') }}"
    dest: '/etc/dovecot/local.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart dovecot' ]

- name: Generate Dovecot sql configuration
  template:
    src: "{{ lookup('template_src', 'etc/dovecot/dovecot-sql.conf.ext.j2') }}"
    dest: '/etc/dovecot/dovecot-sql.conf.ext'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: [ 'Restart dovecot' ]
  when: "'sql' in dovecot_user_accounts"

- name: Generate Dovecot deny user list
  template:
    src: "{{ lookup('template_src', 'etc/dovecot/dovecot.deny.j2') }}"
    dest: '/etc/dovecot/dovecot.deny'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure firewall for Dovecot
  template:
    src: 'etc/ferm/filter-input.d/dovecot.conf.j2'
    dest: '/etc/ferm/filter-input.d/dovecot.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Restart ferm' ]
  when: (dovecot_firewall is defined and dovecot_firewall)

- name: Create private directory to store passwdfile
  file:
    path: "{{ dovecot_passwdfile_path }}"
    state: directory
    owner: 'root'
    group: 'dovecot'
    mode: '0650'
  when: "'passwdfile' in dovecot_user_accounts"

- name: Create group used in passwdfile
  user:
    name: "{{ dovecot_passwdfile_gid }}"
    system: yes
  when: "'passwdfile' in dovecot_user_accounts"

- name: Create user used in passwdfile
  user:
    name: "{{ dovecot_passwdfile_uid }}"
    group: "{{ dovecot_passwdfile_gid }}"
    home: "{{ dovecot_passwdfile_home }}"
    shell: "/usr/sbin/nologin"
    system: yes
  when: "'passwdfile' in dovecot_user_accounts"

- name: Post hooks
  include: "{{ lookup('task_src', 'dovecot/post_main.yml') }}"
