---

sudo: 'required'
language: 'python'

matrix:
  include:

    - python: '2.7'
      env: 'MODE=docs'

    - python: '2.7'
      env: 'MODE=syntax'

    - python: '2.7'
      env: 'MODE=docker'

    - python: '2.7'
      env: 'MODE=build-sdist'

    - python: '3.6'
      env: 'MODE=ansible'

    - python: '3.5'
      env: 'MODE=ansible'

    - python: '2.7'
      env: 'MODE=ansible'

    - python: '3.6'
      env: 'MODE=build-wheel'

    - python: '3.5'
      env: 'MODE=build-wheel'

    - python: '2.7'
      env: 'MODE=build-wheel'

    - python: '3.6'
      env: 'MODE=test'

    - python: '3.5'
      env: 'MODE=test'

    - python: '2.7'
      env: 'MODE=test'

virtualenv:
  system_site_packages: false

services:
  - 'docker'

cache:
  directories:
    - '$HOME/.cache/pip'

before_install:
  - "${TRAVIS_BUILD_DIR}/lib/travis/${MODE}/before_install.sh"

install:
  - "${TRAVIS_BUILD_DIR}/lib/travis/${MODE}/install.sh"

script:
  - "${TRAVIS_BUILD_DIR}/lib/travis/${MODE}/script.sh"
