---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.memcached default variables
# ==================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# .. envvar:: memcached_bind [[[
#
# IP address on which ``memcached`` listens for new connections. To listen on
# all interfaces, set it to ``0.0.0.0``.
memcached_bind: '127.0.0.1'

                                                                   # ]]]
# .. envvar:: memcached_allow [[[
#
# List of IP addresses or CIDR subnets which are allowed to connect to this
# ``memcached``. If the list is empty, remote connections are denied.
memcached_allow: []

                                                                   # ]]]
# .. envvar:: memcached_memory [[[
#
# Maximum amount of RAM ``memcached`` is allowed to use.
memcached_memory: '{{ (memcached_memory_available  | float *
                       memcached_memory_multiplier | float) | int }}'

                                                                   # ]]]
# .. envvar:: memcached_memory_available [[[
#
# Amount of RAM which ``debops.memcached`` takes into account while calculating
# ``memcached_memory`` variable.
memcached_memory_available: '{{ ansible_memtotal_mb }}'

                                                                   # ]]]
# .. envvar:: memcached_memory_multiplier [[[
#
# Value which is multiplied by amount of available RAM to limit memory
# accessible to ``memcached``. 1.0 will allow access to all available memory,
# values bigger than 1.0 don't make much sense.
memcached_memory_multiplier: '0.3'

                                                                   # ]]]
# .. envvar:: memcached_connections [[[
#
# Maximum number of allowed connections.
memcached_connections: '1024'

                                                                   # ]]]
# .. envvar:: memcached_options [[[
#
# Additional ``memcached`` options, specified as YAML text block.
memcached_options: ''

                                                                   # ]]]
