---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'dovecot'
  author: 'Reto Gantenbein'
  description: 'Configure Dovecot IMAP/POP3 service'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - imap
    - pop3
    - sieve
    - mail
