---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'system_groups'
  author: 'Maciej Delmanowski'
  description: 'Manage UNIX system groups'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - system
    - access
    - authz
    - acl
    - sudo
    - ssh
