---

dependencies:

  - role: debops.secret

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'users'
  author: 'Maciej Delmanowski'
  description: 'Create and manage user accounts using Ansible inventory'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - users
    - groups
