---

dependencies: []

galaxy_info:

  role_name: 'cron'
  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Manage cron jobs using Ansible inventory'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
        - xenial

  galaxy_tags:
    - system
    - cron
