---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'tinc'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Configure tinc mesh VPN network'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - networking
    - tinc
    - vpn
