---

- import_playbook: ifupdown.yml

- import_playbook: radvd.yml

- import_playbook: dhcpd.yml

- import_playbook: unbound.yml

- import_playbook: dnsmasq.yml

- import_playbook: tinc.yml

- import_playbook: dhcp_probe.yml

- import_playbook: stunnel.yml

- import_playbook: avahi.yml
