---

- name: Install required packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ users__base_packages }}'
    - '{{ users__packages }}'
  when: users__enabled | bool

- name: DebOps pre_tasks hook
  include: "{{ lookup('task_src', 'users/pre_main.yml') }}"

- include: users.yml
  when: users__enabled | bool

- include: forward.yml
  when: users__enabled | bool

- include: sshkeys.yml
  when: users__enabled | bool

- include: resources.yml
  when: users__enabled | bool

- include: dotfiles.yml
  when: users__enabled | bool
  tags: [ 'role::users:dotfiles' ]

- name: DebOps post_tasks hook
  include: "{{ lookup('task_src', 'users/post_main.yml') }}"
