---

- name: Configure ~/.ssh/authorized_keys for users
  authorized_key:
    key: "{{ (item.sshkeys if item.sshkeys is string else '\n'.join(item.sshkeys)) | string }}"
    state: 'present'
    user: '{{ item.name }}'
    exclusive: '{{ item.sshkeys_exclusive | d(omit) }}'
  with_flattened:
    - '{{ users__root_accounts }}'
    - '{{ users__default_accounts }}'
    - '{{ users__admin_accounts }}'
    - '{{ users__accounts }}'
    - '{{ users__group_accounts }}'
    - '{{ users__host_accounts }}'
    - '{{ users__dependent_accounts }}'
  when: (item.name|d() and item.state|d('present') != 'absent' and item.createhome|d(True) and
         item.sshkeys|d() and item.sshkeys_state|d('present') != 'absent')
  no_log: '{{ users__no_log | bool }}'

- name: Remove ~/.ssh/authorized_keys from user account if disabled
  file:
    path: '~{{ item.name }}/.ssh/authorized_keys'
    state: 'absent'
  with_flattened:
    - '{{ users__root_accounts }}'
    - '{{ users__default_accounts }}'
    - '{{ users__admin_accounts }}'
    - '{{ users__accounts }}'
    - '{{ users__group_accounts }}'
    - '{{ users__host_accounts }}'
    - '{{ users__dependent_accounts }}'
  when: (item.name|d() and item.state|d('present') != 'absent' and item.createhome|d(True) and
         item.sshkeys_state|d('present') == 'absent')
  no_log: '{{ users__no_log | bool }}'
