---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.tftpd default variables
# ==============================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# .. envvar:: tftpd_address [[[
#
# Address and port on which ``tftpd-hpa`` server is listening
tftpd_address: '[::]:69'

                                                                   # ]]]
# .. envvar:: tftpd_directory [[[
#
# Root directory with files served over TFTP
tftpd_directory: '/srv/tftp'

                                                                   # ]]]
# .. envvar:: tftpd_username [[[
#
# System user account used by ``tftpd-hpa`` daemon
tftpd_username: 'tftp'

                                                                   # ]]]
# .. envvar:: tftpd_options [[[
#
# Additional options passed to ``tftpd-hpa`` daemon
tftpd_options: '--secure'

                                                                   # ]]]
# .. envvar:: tftpd_allow [[[
#
# List of IP addresses or CIDR networks which are allowed to connect to TFTP
# server. If it's empty, anybody can connect to the FTP server.
tftpd_allow: []

                                                                   # ]]]
