---

dependencies: []

galaxy_info:

  role_name: 'ferm'
  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider, Reto Gantenbein'
  description: 'Manage iptables firewall using ferm'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

  galaxy_tags:
    - system
    - networking
    - security
    - firewall
