---

- name: Setup and manage the server-side of X2Go
  hosts: [ 'debops_service_x2go_server' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops-contrib.x2go_server
      tags: [ 'role::x2go_server' ]
