---

dependencies: []

galaxy_info:

  role_name: 'elastic_co'
  author: 'Maciej Delmanowski'
  description: 'Configure Elastic APT repositories'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - clustering
    - database
    - nosql
    - search
    - elasticsearch
    - kibana
    - logstash
    - filebeat
    - metricbeat
    - packetbeat
    - heartbeat
