---

dependencies: []

galaxy_info:

  role_name: 'rsyslog'
  author: 'Maciej Delmanowski'
  description: 'Manage rsyslog configuration'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - system
    - logging
    - logs
    - security
    - audit
