---

allow_duplicates: True

dependencies: []

galaxy_info:

  role_name: 'apt_preferences'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage APT pins in /etc/apt/preferences.d/'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '1.7.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - system
    - apt
