---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'apt_mark'
  author: 'Maciej Delmanowski'
  description: 'Set desired APT package state using apt-mark'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - system
    - apt
