---

dependencies:

  - role: debops.secret

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'roundcube'
  company: 'DebOps'
  author: 'Reto Gantenbein'
  description: 'Manage Roundcube, a browser-based IMAP client written in PHP'
  license: 'GPL-3.0'
  min_ansible_version: '2.3.0'

  platforms:

    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - zesty

    - name: Debian
      versions:
        - jessie
        - stretch
        - buster

  galaxy_tags:
    - debops
    - email
    - mail
    - imap
    - web
