---

dependencies: []

galaxy_info:

  role_name: 'ruby'
  author: 'Maciej Delmanowski'
  description: 'Install Ruby packages and gems'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - development
  - programming
  - ruby
  - gems
