---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'rabbitmq_server'
  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Manage RabbitMQ service'
  license: 'GPL-3.0'
  min_ansible_version: '2.3.0'

  platforms:

    - name: Ubuntu
      versions:
        - trusty
        - xenial

    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - amqp
    - stomp
    - mqtt
    - broker
    - queue
    - networking
