---

dependencies:

  - role: debops.secret

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'resources'
  author: 'Maciej Delmanowski'
  description: 'Manage custom file resources through Ansible inventory'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - files
    - directories
    - urls
    - paths
    - archives
    - repositories
