---

dependencies:

  - role: debops.secret
    tags: [ 'depend::secret', 'depend::secret:cryptsetup',
            'depend-of::cryptsetup', 'type::dependency:hard' ]

galaxy_info:

  role_name: 'cryptsetup'
  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Setup and manage encrypted filesystems'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.3'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch

  galaxy_tags:
    - encryption
    - security
    - filesystem
    - cryptsetup
    - dmcrypt
    - luks
