---

dependencies:

  - role: debops.secret

  - role: debops.nginx
    nginx_servers:
      - '{{ reprepro_nginx_server_http }}'
      - '{{ reprepro_nginx_server_https }}'
    tags: nginx

galaxy_info:

  role_name: 'reprepro'
  author: 'Maciej Delmanowski'
  description: 'Create local APT repository with reprepro'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.9.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - development
    - packaging
    - apt
    - repository
