---

dependencies: []

galaxy_info:

  role_name: 'nodejs'
  author: 'Maciej Delmanowski'
  description: 'Install NodeJS and NPM packages'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - development
    - nodejs
    - npm
