---

- name: Update PAM common configuration
  shell: pam-auth-update --package libpam-modules 2>/dev/null
  when: ansible_distribution_release not in ["bionic", "buster"]

- name: Enable mkhomedir PAM module
  shell: pam-auth-update --enable mkhomedir 2>/dev/null
  when: ansible_distribution_release in ["bionic", "buster"]
