---

- name: Configure volume snapshots with snapper
  hosts: [ 'debops_service_snapshot_snapper' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops-contrib.snapshot_snapper
      tags: [ 'role::snapshot_snapper' ]
