---

dependencies: []

galaxy_info:

  role_name: 'debops_fact'
  author: 'Maciej Delmanowski'
  description: 'Manage Ansible local facts for other roles'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - ansible
    - ipc
    - facts
