---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.sftpusers default variables
# ==================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# ---- An example account entry ----

# Everything except 'name', 'dirs' and 'sites' is optional
# List of all recognized values, default value listed first
#
#  - name: 'username'               # mandatory, default group if not defined
#
#    # Required, can be empty. Create directories in user home directory
#    dirs: [ 'files', 'dir/subdir', 'directory\ with\ spaces' ]
#
#    # Required, can be empty. Prepare site directories for websites and mount
#    # them in the users' home directory in $HOME/sites/
#    sites: [ 'example.com', 'other.example.com' ]
#
#    state: 'present,absent'
#    group: 'name'                  # default group
#    gid: ''
#    uid: ''
#    comment: 'GECOS entry'
#    systemuser: False/True         # create system user
#    systemgroup: False/True        # create system group
#
#    home: '/srv/sftpusers/name'
#
#    # Create ~/.forward file (set to False to remove ~/.forward)
#    forward: [ 'user@domain', 'account' ]
#


# ---- Lists of different accounts to create/manage ----

# .. envvar:: sftpusers_list [[[
#
# "Global" users
sftpusers_list: []

                                                                   # ]]]
# .. envvar:: sftpusers_group_list [[[
#
# "Host group" users
sftpusers_group_list: []

                                                                   # ]]]
# .. envvar:: sftpusers_host_list [[[
#
# "Host" users
sftpusers_host_list: []

                                                                   # ]]]
# ---- Global defaults ----

# .. envvar:: sftpusers_name_suffix [[[
#
# Add a suffix to an account name, for example: '-sftp'
sftpusers_name_suffix: ""

                                                                   # ]]]
# .. envvar:: sftpusers_system_group [[[
#
# System group that restricts account use to SFTPonly
sftpusers_system_group: 'sftponly'

                                                                   # ]]]
# .. envvar:: sftpusers_default_shell [[[
#
# Shell enforced on all SFTPonly accounts
sftpusers_default_shell: '/usr/sbin/nologin'

                                                                   # ]]]
# .. envvar:: sftpusers_default_groups [[[
#
# List of groups SFTPonly users belong in
sftpusers_default_groups: [ '{{ sftpusers_system_group }}' ]

                                                                   # ]]]
# .. envvar:: sftpusers_default_www_prefix [[[
#
# Path to directory where websites are stored
sftpusers_default_www_prefix: '/srv/www'

                                                                   # ]]]
# .. envvar:: sftpusers_default_www_group [[[
#
# System group which should be allowed access to website directory
sftpusers_default_www_group: 'www-data'

                                                                   # ]]]
# .. envvar:: sftpusers_default_mount_options [[[
#
# Mount options used to mount website directories in user home directories
# (sftponly users don't have access to directories outside of their home
# directory (/srv/sftpusers/username). Because of that website directories
# (/srv/www/username/sites/) will be bind mounted to their home directories
# (/srv/sftpusers/username/sites/), thus allowing secure access)
sftpusers_default_mount_options: 'bind'

                                                                   # ]]]
# .. envvar:: sftpusers_default_home_prefix [[[
#
# Directory where SFTPonly user homes will be created
sftpusers_default_home_prefix: '/srv/sftpusers'

                                                                   # ]]]
# .. envvar:: sftpusers_default_home_mode [[[
#
# UNIX permissions enforced on users home directories
sftpusers_default_home_mode: '0750'

                                                                   # ]]]
# .. envvar:: sftpusers_default_dirs [[[
#
# List of default directories created on SFTPonly accounts (users don't have
# permission to access their home directory due to SFTPonly constraints, but they
# can access subdirectories)
sftpusers_default_dirs: [ 'files' ]

                                                                   # ]]]
