---

dependencies:

  - role: debops.secret
    tags: [ 'role::secret' ]

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'gitlab'
  author: 'Maciej Delmanowski'
  description: 'Install, upgrade and manage GitLab instance'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.0'
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - zesty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - gitlab
    - gitlabci
    - git
    - webapp
    - rails
    - development
    - programming
    - ci
