---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'librenms'
  author: 'Maciej Delmanowski'
  description: 'Install LibreNMS, an Open Source Network Monitoring System'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - monitoring
    - network
    - librenms
    - nms
    - snmp
    - alerts
