---

- include: dist_vars.yml
- include: install.yml

- name: Get list of nameservers configured in /etc/resolv.conf
  shell: grep -E '^nameserver\s' /etc/resolv.conf | awk '{print $2}'
  register: dhcpd_register_nameservers
  changed_when: False
  when: dhcpd_mode == 'server'
  check_mode: False

- name: Convert list of nameservers to Ansible list
  set_fact:
    dhcpd_runtime_nameservers: "{{ dhcpd_register_nameservers.stdout_lines }}"
  when: (dhcpd_register_nameservers is defined and dhcpd_register_nameservers.stdout|d())

- name: Configure DHCP server
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ dhcpd_templates }}"
  notify: [ 'Restart dhcp server' ]
  register: dhcpd_register_config
  when: dhcpd_mode == 'server'

- name: Make sure that included files exist
  file:
    path: '{{ item }}'
    state: 'touch'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ dhcpd_includes }}'
  notify: [ 'Restart dhcp server' ]
  when: ((item is defined and item) and dhcpd_mode == 'server' and
         (dhcpd_register_config is defined and dhcpd_register_config is changed))

- name: Make sure that IPv6 lease file exists
  command: touch /var/lib/dhcp/dhcpd6.leases creates=/var/lib/dhcp/dhcpd6.leases
  when: dhcpd_ipversion == '6'
