---

- name: Mark APT package state
  hosts: [ 'debops_all_hosts', 'debops_service_apt_mark' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_mark
      tags: [ 'role::apt_mark', 'skip::apt_mark' ]
