---

- name: Manage ISC DHCP server
  hosts: [ 'debops_service_dhcpd', 'debops_dhcpd' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.dhcpd
      tags: [ 'role::dhcpd', 'skip::dhcpd' ]
