---

- name: Manage GitLab CI service
  hosts: [ 'debops_service_gitlab_ci', 'debops_gitlab_ci' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.gitlab_ci
      tags: [ 'role::gitlab_ci' ]
