---

- name: Manage GitLab service
  hosts: [ 'debops_service_gitlab' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.gitlab/env
      tags: [ 'role::gitlab', 'role::postgresql' ]

    - role: debops.system_groups
      tags: [ 'role::system_groups', 'skip::system_groups' ]

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ golang__apt_preferences__dependent_list }}'
        - '{{ nginx__apt_preferences__dependent_list }}'
        - '{{ nodejs__apt_preferences__dependent_list }}'
        - '{{ postgresql__apt_preferences__dependent_list }}'
        - '{{ ruby__apt_preferences__dependent_list }}'
        - '{{ gitlab__apt_preferences__dependent_list }}'

    - role: debops.golang
      tags: [ 'role::golang', 'skip::golang' ]

    - role: debops.nodejs
      tags: [ 'role::nodejs', 'skip::nodejs' ]
      nodejs__upstream: True
      nodejs__yarn_upstream: True

    - role: debops.etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ gitlab__etc_services__dependent_list }}'

    - role: debops.logrotate
      tags: [ 'role::logrotate', 'skip::logrotate' ]
      logrotate__dependent_config:
        - '{{ gitlab__logrotate__dependent_config }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'

    - role: debops.ruby
      tags: [ 'role::ruby', 'skip::ruby' ]
      ruby__dev_support: True

    - role: debops.postgresql
      tags: [ 'role::postgresql', 'skip::postgresql' ]
      postgresql__dependent_roles:
        - '{{ gitlab__postgresql__dependent_roles }}'
      postgresql__dependent_groups:
        - '{{ gitlab__postgresql__dependent_groups }}'
      postgresql__dependent_databases:
        - '{{ gitlab__postgresql__dependent_databases }}'
      postgresql__dependent_extensions:
        - '{{ gitlab__postgresql__dependent_extensions }}'
      postgresql__dependent_pgpass:
        - '{{ gitlab__postgresql__dependent_pgpass }}'
      when: gitlab__database == 'postgresql'

    - role: debops.nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx__dependent_servers:
        - '{{ gitlab__nginx__dependent_servers }}'
      nginx__dependent_upstreams:
        - '{{ gitlab__nginx__dependent_upstreams }}'

    - role: debops.gitlab
      tags: [ 'role::gitlab', 'skip::gitlab' ]
