---

- name: Manage Go environment
  hosts: [ 'debops_service_golang', 'debops_golang' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ golang__apt_preferences__dependent_list }}'

    - role: debops.golang
      tags: [ 'role::golang', 'skip::golang' ]
