---

- name: Configure HWRaid support
  hosts: [ 'debops_service_hwraid', 'debops_hwraid' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.hwraid
      tags: [ 'role::hwraid', 'skip::hwraid' ]
