---

- name: Manage PostgreSQL server
  hosts: [ 'debops_service_postgresql_server', 'debops_postgresql_server' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ postgresql_server__apt_preferences__dependent_list }}'

    - role: debops.etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ postgresql_server__etc_services__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ postgresql_server__ferm__dependent_rules }}'

    - role: debops.locales
      tags: [ 'role::locales', 'skip::locales' ]
      locales__dependent_list:
        - '{{ postgresql_server__locales__dependent_list }}'

    - role: debops.postgresql_server
      tags: [ 'role::postgresql_server', 'skip::postgresql_server' ]
