---

- name: Manage Postfix postscreen configuration
  hosts: [ 'debops_service_postscreen' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.postfix/env
      tags: [ 'role::postfix', 'role::secret' ]

    - role: debops.secret
      tags: [ 'role::secret', 'role::postfix' ]
      secret__directories:
        - '{{ postfix__secret__directories }}'

    - role: debops.postfix
      tags: [ 'role::postfix', 'skip::postfix' ]
      postfix__dependent_packages:
        - '{{ postscreen__postfix__dependent_packages }}'
      postfix__dependent_maincf:
        - role: 'postscreen'
          config: '{{ postscreen__postfix__dependent_maincf }}'
      postfix__dependent_mastercf:
        - role: 'postscreen'
          config: '{{ postscreen__postfix__dependent_mastercf }}'

    - role: debops.postscreen
      tags: [ 'role::postscreen', 'skip::postscreen' ]
