---

dependencies: []

galaxy_info:

  role_name: 'logrotate'
  author: 'Maciej Delmanowski'
  description: 'Manage log rotation configuration'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - system
    - logs
