---

- name: Install required packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ saslauthd__base_packages }}'
    - '{{ saslauthd__packages }}'

- name: Stop saslauthd instance before removal
  command: /etc/init.d/saslauthd stop-instance saslauthd-{{ item.name }}
  with_items: '{{ saslauthd__combined_instances | parse_kv_items }}'
  when: item.name|d() and item.socket_path|d() and
        item.state|d('present') == 'absent'

- name: Remove saslauthd instance if requested
  file:
    path: '/etc/default/saslauthd-{{ item.name }}'
    state: 'absent'
  with_items: '{{ saslauthd__combined_instances | parse_kv_items }}'
  when: item.name|d() and item.socket_path|d() and
        item.state|d('present') == 'absent'

- name: Generate saslauthd configuration
  template:
    src: 'etc/default/saslauthd.j2'
    dest: '/etc/default/saslauthd-{{ item.name }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ saslauthd__combined_instances | parse_kv_items }}'
  notify: [ 'Restart saslauthd' ]
  when: item.name|d() and item.socket_path|d() and
        item.state|d('present') != 'absent'

- name: Ensure that required UNIX groups exist
  group:
    name: '{{ item.group }}'
    state: 'present'
    system: '{{ (item.system | d(True)) | bool }}'
  with_items: '{{ saslauthd__combined_instances | parse_kv_items }}'
  when: item.name|d() and item.group|d() and
        item.state|d('present') != 'absent'

- name: Create SASL config directory
  file:
    path: '{{ item.config_path | dirname }}'
    state: 'directory'
    owner: '{{ item.config_dir_owner | d("root") }}'
    group: '{{ item.config_dir_group | d("root") }}'
    mode: '{{ item.config_dir_mode   | d("0755") }}'
  with_items: '{{ saslauthd__combined_instances | parse_kv_items }}'
  when: item.name|d() and item.config_path|d() and
        item.state|d('present') != 'absent'

- name: Generate SASL configuration
  template:
    src: 'etc/saslauthd.conf.j2'
    dest: '{{ item.config_path }}'
    owner: '{{ item.config_owner | d("root") }}'
    group: '{{ item.config_group | d("sasl") }}'
    mode: '{{ item.config_mode | d("0640") }}'
  with_items: '{{ saslauthd__combined_instances | parse_kv_items }}'
  when: item.name|d() and item.config_path|d() and
        item.state|d('present') != 'absent'

- name: Get list of dpkg-stateoverride paths
  shell: dpkg-statoverride --list | awk '{print $4}'
  register: saslauthd__register_statoverride
  changed_when: False
  check_mode: False

- name: Remove a dpkg-statoverride entry if requested
  command: dpkg-statoverride --remove {{ item.socket_path }}
  with_items: '{{ saslauthd__combined_instances | parse_kv_items }}'
  notify: [ 'Restart saslauthd' ]
  when: item.name|d() and item.socket_path|d() and item.state|d('present') == 'absent' and
        item.socket_path in saslauthd__register_statoverride.stdout_lines

- name: Create a dpkg-statoverride entry
  command: dpkg-statoverride --add
           {{ item.socket_owner | d('root') }}
           {{ item.socket_group | d('sasl') }}
           {{ item.socket_mode  | d('710') }}
           {{ item.socket_path }}
  with_items: '{{ saslauthd__combined_instances | parse_kv_items }}'
  notify: [ 'Restart saslauthd' ]
  when: item.name|d() and item.socket_path|d() and item.state|d('present') != 'absent' and
        item.socket_path not in saslauthd__register_statoverride.stdout_lines

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save saslauthd local facts
  template:
    src: 'etc/ansible/facts.d/saslauthd.fact.j2'
    dest: '/etc/ansible/facts.d/saslauthd.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: saslauthd__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: saslauthd__register_facts is changed
