---

- name: Make sure libldap is installed
  apt:
    name: 'libldap-2.4-2'
    state: 'present'
    install_recommends: False

- name: Divert original LDAP configuration
  command: dpkg-divert --quiet --local --divert /etc/ldap/ldap.conf.dpkg-divert --rename /etc/ldap/ldap.conf
           creates=/etc/ldap/ldap.conf.dpkg-divert

- name: Configure system-wide LDAP access
  template:
    src: '{{ lookup("template_src", "etc/ldap/ldap.conf.j2") }}'
    dest: '/etc/ldap/ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
