---

- name: DebOps pre_tasks hook
  include: "{{ lookup('task_src', 'auth/pre_main.yml') }}"

- name: Install auth-related packages
  apt:
    name: '{{ auth_packages | flatten }}'
    state: 'present'
    install_recommends: 'no'
  register: auth__register_packages
  until: auth__register_packages is succeeded

- name: Configure pam_cracklib
  template:
    src: 'usr/share/pam-configs/cracklib.j2'
    dest: '/usr/share/pam-configs/cracklib'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Update PAM common configuration', 'Enable mkhomedir PAM module' ]
  when: auth_cracklib|bool

- name: Configure PAM password history module
  include: pam_pwhistory.yml
  when: auth_pwhistory_remember is defined and auth_pwhistory_remember

- name: Check if /etc/ldap exists
  stat:
    path: '/etc/ldap'
  register: auth_register_etc_ldap

- include: etc_ldap_conf.yml
  when: ((auth_ldap_conf|bool) and
         ((auth_register_etc_ldap.stat.exists) or
          ('ldap' in auth_nsswitch)))

- include: nss_pam_ldap.yml
  when: (('ldap' in auth_nsswitch) and (auth_nslcd_conf|bool))

- name: DebOps post_tasks hook
  include: "{{ lookup('task_src', 'auth/post_main.yml') }}"
