---

- name: Configure pam-mkhomedir for LDAP authentication
  template:
    src: 'usr/share/pam-configs/mkhomedir.j2'
    dest: '/usr/share/pam-configs/mkhomedir'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Update PAM common configuration' ]

- name: Install packages require for LDAP authentication
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_items: [ 'libnss-ldapd', 'libpam-ldapd', 'openssl', 'ca-certificates' ]

- name: Divert original /etc/nslcd.conf
  command: dpkg-divert --quiet --local --divert /etc/nslcd.conf.dpkg-divert --rename /etc/nslcd.conf
           creates=/etc/nslcd.conf.dpkg-divert

- include: machine_bind_account.yml
  when: auth_nslcd_ldap_server is defined and auth_nslcd_ldap_server

- name: Configure nslcd for LDAP authentication
  template:
    src: '{{ lookup("template_src", "etc/nslcd.conf.j2") }}'
    dest: '/etc/nslcd.conf'
    owner: 'root'
    group: 'nslcd'
    mode: '0640'
  register: auth_register_nslcd_conf

- name: Restart nslcd if configuration changed
  service:
    name: 'nslcd'
    state: 'restarted'
  when: auth_register_nslcd_conf is defined and auth_register_nslcd_conf is changed
