---

dependencies: []

galaxy_info:

  role_name: 'cran'
  author: 'Maciej Delmanowski'
  description: 'Manage the Comprehensive R Archive Network (CRAN) packages'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.3.0'
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - cran
    - rlang
    - rstudio
    - programming
    - development
    - statistics
