---

dependencies: []

galaxy_info:

  role_name: 'tcpwrappers'
  author: 'Maciej Delmanowski'
  description: 'Manage host access rules in /etc/hosts.{allow,deny}'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - security
    - tcpwrappers
    - networking
