---

- name: Configure ~/.forward file for users
  template:
    src: 'srv/sftpusers/forward.j2'
    dest: '{{ item.home | default(sftpusers_default_home_prefix + "/" + item.name + sftpusers_name_suffix) }}/.forward'
    owner: '{{ item.name + sftpusers_name_suffix }}'
    group: '{{ item.group | default(item.name + sftpusers_name_suffix) }}'
    mode: '0644'
  with_flattened:
    - '{{ sftpusers_list }}'
    - '{{ sftpusers_group_list }}'
    - '{{ sftpusers_host_list }}'
  when: ((item.name is defined and item.name) and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.forward is defined and item.forward))

- name: Remove ~/.forward file from user account when disabled
  file:
    dest: '{{ item.home | default(sftpusers_default_home_prefix + "/" + item.name + sftpusers_name_suffix) }}/.forward'
    state: 'absent'
  with_flattened:
    - '{{ sftpusers_list }}'
    - '{{ sftpusers_group_list }}'
    - '{{ sftpusers_host_list }}'
  when: ((item.name is defined and item.name) and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.forward is defined and item.forward == False))
