---

- name: Remove user groups if requested
  group:
    name: '{{ item.group | default(item.name + sftpusers_name_suffix) }}'
    state: 'absent'
  with_flattened:
    - '{{ sftpusers_list }}'
    - '{{ sftpusers_group_list }}'
    - '{{ sftpusers_host_list }}'
  when: ((item.name is defined and item.name) and
        (item.state is defined and item.state == 'absent'))
