---

- name: Create directory for specific user homes
  file:
    path: '{{ sftpusers_default_home_prefix }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0751'

- name: Make sure SFTPonly system group is present
  group:
    name: '{{ sftpusers_system_group }}'
    system: 'yes'
    state: 'present'

- include: groups_present.yml
- include: sftpusers.yml
- include: dirs.yml
- include: sites.yml
- include: forward.yml
- include: groups_absent.yml
