---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'netbox'
  author: 'Maciej Delmanowski'
  description: 'Deploy and manage NetBox, IPAM/DCIM management tool'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - ipam
    - dcim
    - django
    - networking
    - datacenter
