---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'root_account'
  company: 'DebOps'
  author: 'Fabio Bonelli'
  description: 'Manage the root account'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Debian
      versions:
        - jessie
        - stretch

    - name: Ubuntu
      versions:
        - xenial
        - yakkety

  galaxy_tags:
    - system
