---

dependencies:
  - role: debops.secret

galaxy_info:

  role_name: 'postgresql_server'
  author: 'Maciej Delmanowski'
  description: 'Install and manage PostgreSQL Server'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '1.9.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - 'postgresql'
    - 'databases'
