---

dependencies:

  - role: debops.secret

  - role: debops.ansible_plugins

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and configure FreeRADIUS'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.6.0'
  platforms:
    - name: Ubuntu
      versions:
        - bionic
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - radius
    - authentication
    - authorization
    - networking
