---

# phpIPAM database schema loaded by Ansible
phpipam_database_schema: '{{ phpipam_git_checkout + "/db/SCHEMA.sql" }}'

# Configuration for php5-fpm pool
phpipam_php5_pool:
  enabled: True
  name: 'phpipam'
  user: '{{ phpipam_user }}'
  group: '{{ phpipam_group }}'

# nginx configuration - PHP5 upstream
phpipam_nginx_upstream_php5:
  enabled: True
  name: 'php5_phpipam'
  type: 'php5'
  php5: 'phpipam'

# nginx configuration - phpIPAM server
phpipam_nginx_server:
  by_role: 'debops.phpipam'
  enabled: True
  type: 'php5'
  name: '{{ phpipam_domain }}'
  root: '{{ phpipam_git_checkout }}'
  access_policy: '{{ phpipam_nginx_access_policy }}'
  auth_basic_realm: '{{ phpipam_nginx_auth_realm }}'
  php5: 'php5_phpipam'

  error_pages:
    '400': '/index.php?page=error&section=400'
    '401': '/index.php?page=error&section=401'
    '403': '/index.php?page=error&section=403'
    '404': '/index.php?page=error&section=404'
    '500': '/index.php?page=error&section=500'

  location:
    '/api': |
      try_files $uri $uri/ /api/index.php?$args =404;

    '/': |
      rewrite ^/login/dashboard/$                 /dashboard/ redirect;
      rewrite ^/logout/dashboard/$                /dashboard/ redirect;
      rewrite ^/tools/search/(.*)/(.*)/(.*)/(.*)$ /index.php?page=tools&section=search&addresses=$1&subnets=$2&vlans=$3&ip=$4 last;
      rewrite ^/(.*)/(.*)/(.*)/(.*)/(.*)/$        /index.php?page=$1&section=$2&subnetId=$3&sPage=$4&ipaddrid=$5 last;
      rewrite ^/(.*)/(.*)/(.*)/(.*)/$             /index.php?page=$1&section=$2&subnetId=$3&sPage=$4 last;
      rewrite ^/(.*)/(.*)/(.*)/$                  /index.php?page=$1&section=$2&subnetId=$3 last;
      rewrite ^/(.*)/(.*)/$                       /index.php?page=$1&section=$2 last;
      rewrite ^/(.*)/$                            /index.php?page=$1 last;
      try_files $uri $uri/ $uri.html $uri.htm /index.html /index.htm =404;
