---

dependencies:

  - role: debops.ansible_plugins

  - role: debops.secret

galaxy_info:

  role_name: 'postconf'
  author: 'Maciej Delmanowski'
  description: 'Configure Postfix SMTP service via debops.postfix'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.3.0'

  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch

  galaxy_tags:
    - smtp
    - mail
    - lmtp
    - submission
    - postfix
    - sasl
    - antispam
