---

dependencies:

  - role: debops.secret

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'pki'
  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Bootstrap and manage internal PKI, Certificate Authorities and OpenSSL/GnuTLS certificates'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

  galaxy_tags:
    - encryption
    - hardening
    - security
    - pki
    - ssl
    - tls
    - acme
    - letsencrypt
