---

dependencies: []

galaxy_info:

  role_name: 'homeassistant'
  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Setup and manage Home Assistant'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.2'

  platforms:

    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - automation
    - home
    - homeassistant
    - iot
