---

dependencies: []

galaxy_info:

  role_name: 'kodi'
  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Setup and manage Kodi'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.5'

  platforms:

    - name: Debian
      versions:
        - stretch

  galaxy_tags:
    - kodi
    - home
    - htpc
    - mediacenter
    - media
    - player
