---

dependencies: []

galaxy_info:

  role_name: 'postscreen'
  author: 'Maciej Delmanowski'
  description: 'Manage Postscreen Postfix service'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.3.0'

  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  - name: Debian
    versions:
    - wheezy
    - jessie
    - stretch

  galaxy_tags:
  - smtp
  - antispam
