---

dependencies: []

galaxy_info:

  role_name: 'python'
  author: 'Maciej Delmanowski'
  description: 'Manage Python environment'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - development
    - pip
    - python
    - python2
    - python3
    - programming
    - virtualenv
