---

dependencies:

  - role: 'debops.ansible_plugins'

  - role: 'debops.secret'

galaxy_info:

  role_name: 'redis_server'
  author: 'Maciej Delmanowski'
  description: 'Configure Redis Server instances'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - redis
