---

dependencies: []

galaxy_info:

  role_name: 'x2go_server'
  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Setup and manage the server-side of X2Go'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.3'

  platforms:

    - name: Debian
      versions:
        - jessie

    - name: Ubuntu
      versions:
        - precise
        - trusty

  galaxy_tags:
    - desktop
    - remote
    - x11
    - ssh
