---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'console'
  author: 'Maciej Delmanowski'
  description: 'Configure system console and terminal-related options'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
