---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'saslauthd'
  author: 'Maciej Delmanowski'
  description: 'Manage Cyrus SASL authentication service'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.3.0'

  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch

  galaxy_tags:
    - security
    - authentication
    - smtp
    - sasl
