---

dependencies: []

galaxy_info:

  role_name: 'dnsmasq'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Install and configure dnsmasq'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  galaxy_tags:
  - system
  - network
  - dhcp
  - dns
