---

dependencies:

  - role: debops.secret

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'slapd'
  author: 'Maciej Delmanowski'
  description: 'Manage slapd - OpenLDAP server'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.8'

  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
    - name: GenericLinux
      versions:
        - all
    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - database
    - ldap
    - auth
