---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'sudo'
  author: 'Maciej Delmanowski'
  description: 'Configure sudo support on a host'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: FreeBSD
      versions:
        - 12.0
  galaxy_tags:
    - sudo
    - authentication
    - authorization
    - security
