---

dependencies: []

galaxy_info:

  role_name: 'hwraid'
  author: 'Maciej Delmanowski'
  description: 'Configure HWRaid repository and install packages for recognized RAID storage arrays'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - monitoring
    - system
    - hardware
    - raid
    - hwraid
