---

dependencies: []

galaxy_info:

  role_name: 'sftpusers'
  author: 'Maciej Delmanowski'
  description: 'Manage user accounts restricted to SFTP access'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - security
    - sftp
