---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'dhparam'
  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage one or multiple sets of Diffie-Hellman Ephemeral parameters'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - encryption
    - security
    - tls
    - ssl
    - pki
    - weakdh
    - logjam
