---

- name: Install requested APT packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened: '{{ python__combined_packages }}'
  when: python__enabled|bool and ansible_pkg_mgr == 'apt'

- name: Install requested packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened: '{{ python__combined_packages }}'
  when: python__enabled|bool and ansible_pkg_mgr != 'apt'

- name: Make sure that Ansible local fact directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save Python local facts
  template:
    src: 'etc/ansible/facts.d/python.fact.j2'
    dest: '/etc/ansible/facts.d/python.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: python__register_facts

- name: Re-read local facts if they have been modified
  action: setup
  when: python__register_facts is changed
