---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'kmod'
  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage kernel modules'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'

  platforms:

    - name: Ubuntu
      versions:
        - xenial
        - bionic

    - name: Debian
      versions:
        - jessie
        - stretch
        - buster

  galaxy_tags:
    - system
    - kernel
    - linux
