---

dependencies: []

galaxy_info:

  role_name: 'docker'
  author: 'Maciej Delmanowski'
  description: 'Install and configure Docker Engine'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '1.9.0'
  platforms:
  - name: Debian
    versions:
    - jessie
    - stretch
  galaxy_tags:
  - virtualization
  - cloud
  - docker
  - containers
