---

dependencies:

  - role: debops.auth

galaxy_info:

  role_name: 'gitusers'
  author: 'Maciej Delmanowski'
  description: 'Manage user accounts based around git-shell'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - git
