---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'mariadb_server'
  author: 'Maciej Delmanowski'
  description: 'Install and manage a MariaDB / MySQL server'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - mariadb
    - mysql
    - percona
    - sql
    - database
