---

dependencies: []

galaxy_info:

  role_name: 'core'
  author: 'Maciej Delmanowski'
  description: 'Install a set of Ansible local facts on remote host'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '1.9.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  galaxy_tags:
  - system
