---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'sysnews'
  author: 'Maciej Delmanowski'
  description: 'Manage System News for UNIX accounts'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
  galaxy_tags:
    - system
    - motd
    - login
    - news
