---

dependencies: []

galaxy_info:

  role_name: 'java'
  author: 'Nick Janetakis'
  description: 'Manage Java OpenJRE/OpenJDK environment'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
  galaxy_tags:
    - java
    - development
    - jre
    - jdk
    - openjdk
    - openjre
