---

dependencies:

  - role: debops.secret

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'grub'
  author: 'Patryk Sciborek, Robin Schneider'
  description: 'Manage GRUB configuration'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - boot
    - bootloader
