---

dependencies: []

galaxy_info:

  role_name: 'libvirtd'
  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage libvirt virtualization host'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.3'

  platforms:

    - name: Ubuntu
      versions:
        - trusty
        - xenial

    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch

  galaxy_tags:
    - virtualization
    - kvm
    - qemu
    - xen
    - lxc
