---

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_items: [ 'pax', 'cpio' ]
  register: ipxe__register_pxeboot_packages
  until: ipxe__register_pxeboot_package is succeeded

- name: Create pxeboot work directory
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - '{{ ipxe_debian_pxeboot_workdir }}'
    - '{{ ipxe_debian_pxeboot_workdir + "/firmware" }}'

- name: Download Debian netboot installer
  get_url:
    url: '{{ ipxe_debian_pxeboot_url }}'
    dest: '{{ ipxe_debian_pxeboot_workdir + "/" + (ipxe_debian_pxeboot_url | basename) }}'

- name: Unpack Debian netboot installer
  unarchive:
    src: '{{ ipxe_debian_pxeboot_workdir + "/" + (ipxe_debian_pxeboot_url | basename) }}'
    dest: '{{ ipxe_tftp_root }}'
    copy: False
    creates: '{{ ipxe_tftp_root + "/pxelinux.0" }}'
  register: ipxe_register_debian_netinst
  when: ipxe_tftp|d()

- name: Fix directory permissions after unarchive
  file:
    path: '{{ ipxe_tftp_root }}'
    state: 'directory'
    mode: '0755'

- name: Copy original Debian netboot initrd
  command: cp {{ ipxe_tftp_root }}/debian-installer/amd64/initrd.gz {{ ipxe_debian_pxeboot_workdir }}/
  args:
    creates: '{{ ipxe_debian_pxeboot_workdir + "/initrd.gz" }}'
  when: ipxe_register_debian_netinst|d() and ipxe_register_debian_netinst is changed

- name: Download non-free firmware
  get_url:
    url: '{{ ipxe_debian_pxeboot_firmware_url }}'
    dest: '{{ ipxe_debian_pxeboot_workdir + "/" + (ipxe_debian_pxeboot_firmware_url | basename) }}'
  register: ipxe_register_firmware
  when: ipxe_debian_pxeboot_firmware|d()

- name: Unpack firmware
  unarchive:
    src: '{{ ipxe_debian_pxeboot_workdir + "/" + (ipxe_debian_pxeboot_firmware_url | basename) }}'
    dest: '{{ ipxe_debian_pxeboot_workdir + "/firmware" }}'
    copy: False
  when: ipxe_register_firmware|d() and ipxe_register_firmware is changed

- name: Create firmware cpio archive
  shell: pax -x sv4cpio -s'%{{ ipxe_debian_pxeboot_workdir }}/firmware%/firmware%'
         -w {{ ipxe_debian_pxeboot_workdir }}/firmware |
         gzip -c > {{ ipxe_debian_pxeboot_workdir }}/firmware.cpio.gz
  when: ipxe_register_firmware|d() and ipxe_register_firmware is changed

- name: Create Debian netboot initrd with firmware
  shell: cat {{ ipxe_debian_pxeboot_workdir + "/initrd.gz" }}
             {{ ipxe_debian_pxeboot_workdir + "/firmware.cpio.gz" }} >
             {{ ipxe_tftp_root + "/debian-installer/amd64/initrd.gz" }}
  when: ipxe_register_firmware|d() and ipxe_register_firmware is changed
