---

- name: Setup and manage Kodi
  hosts: [ 'debops_service_kodi' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops-contrib.kodi
      tags: [ 'role::kodi' ]
