---

- name: Add OpenLDAP system user to additional groups
  user:
    name: 'openldap'
    groups: '{{ slapd_append_groups | join(",") | default(omit) }}'
    append: True
    state: 'present'
  notify: [ 'Restart slapd' ]
  when: slapd_pki|d() and slapd_pki | bool

- name: Check if TLS certificate is configured
  shell: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn=config -s base 'olcTLSCertificateFile=*' olcTLSCertificateFile
  register: slapd_register_tls_cert_search
  changed_when: False

- name: Create random temporary directory for ldif file
  command: mktemp -d
  register: slapd_register_tempdir
  when: slapd_pki|d() and slapd_pki | bool and not (slapd_register_tls_cert_search.stdout is search("olcTLSCertificateFile:"))

- name: Prepare temporary ldif file
  template:
    src: 'tmp/configure_tlscerts.ldif.j2'
    dest: '{{ slapd_register_tempdir.stdout|d() + "/configure_tlscerts.ldif" }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: slapd_pki|d() and slapd_pki | bool and not (slapd_register_tls_cert_search.stdout is search("olcTLSCertificateFile:"))

- name: Restart slapd (first time only)
  service:
    name: 'slapd'
    state: 'restarted'
  when: slapd_pki|d() and slapd_pki | bool and not (slapd_register_tls_cert_search.stdout is search("olcTLSCertificateFile:"))

- name: Configure TLS certificates (first time only)
  shell: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ slapd_register_tempdir.stdout|d() + "/configure_tlscerts.ldif" }}'
  when: slapd_pki|d() and slapd_pki | bool and not (slapd_register_tls_cert_search.stdout is search("olcTLSCertificateFile:"))

- name: Configure TLS certificates
  ldap_attr:
    dn: 'cn=config'
    name: '{{ item.key }}'
    values: '{{ item.value }}'
    state: 'exact'
  with_dict:
    olcTLSCACertificateFile:  '{{ slapd_pki_path + "/" + slapd_pki_realm + "/" + slapd_pki_ca }}'
    olcTLSCertificateFile:    '{{ slapd_pki_path + "/" + slapd_pki_realm + "/" + slapd_pki_crt }}'
    olcTLSCertificateKeyFile: '{{ slapd_pki_path + "/" + slapd_pki_realm + "/" + slapd_pki_key }}'
    olcTLSDHParamFile:        '{{ slapd_dhparam_file }}'
    olcTLSCipherSuite:        '{{ slapd_pki_ciphers }}'
  when: slapd_pki|d() and slapd_pki | bool
