---

dependencies:

  - role: debops.ansible_plugins

  - role: debops.secret

galaxy_info:

  role_name: 'opendkim'
  author: 'Maciej Delmanowski'
  description: 'Install and configure OpenDKIM service'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.3.0'

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - smtp
    - milter
    - dkim
    - spf
    - dmarc
    - mail
    - security
    - antispam
