---

- name: Pre hooks
  include: '{{ lookup("task_src", "roundcube/pre_main.yml") }}'


# ---- Environment ----

- name: Get version of current Roundcube installation
  command: sed -n "s/^define('RCMAIL_VERSION', '\(.*\)');/\1/p" \
           {{ roundcube__git_checkout }}/program/include/iniset.php
  args:
    warn: False
  changed_when: False
  failed_when: False
  register: roundcube__register_version
  tags: [ 'role::roundcube:database' ]

# this task is necessary, to trigger proper database upgrades after
# updating the role to v0.2.0 because the default installation path
# has changed.
- name: Get version of deprecated Roundcube installation on role upgrade
  command: sed -n "s/^define('RCMAIL_VERSION', '\(.*\)');/\1/p" \
           /srv/www/roundcube/sites/{{
               roundcube__domain if roundcube__domain is string
               else roundcube__domain[0] }}/public/program/include/iniset.php
  args:
    warn: False
  changed_when: False
  failed_when: False
  register: roundcube__register_version_old
  when: (not roundcube__register_version.stdout|d()) and
        (not roundcube__git_checkout == '/srv/www/roundcube/sites/'
         + (roundcube__domain if roundcube__domain is string
                              else roundcube__domain[0]) + '/public')
  tags: [ 'role::roundcube:database' ]


# ---- Deployment ----

- name: Install pre-requisite packages for Roundcube
  apt:
    pkg: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ roundcube__base_packages }}'
    - '{{ roundcube__packages }}'
    - '{{ roundcube__composer_packages
          if not roundcube__composer_phar|bool else [] }}'
  register: roundcube__register_packages
  until: roundcube__register_packages is succeeded
  tags: [ 'role::roundcube:pkg' ]

- include: deploy_roundcube.yml
  tags: [ 'role::roundcube:deployment' ]


# ---- Configuration ----

- name: Make sure database directory exists
  file:
    path: '{{ roundcube__git_checkout }}/{{ roundcube__database_map[roundcube__database].dbname | dirname }}'
    state: directory
    owner: '{{ roundcube__user }}'
    group: '{{ roundcube__group }}'
    mode: '0750'
  when: roundcube__database_map[roundcube__database].dbtype == 'sqlite'
  tags: [ 'role::roundcube:database' ]

- include: configure_mysql.yml
  when: roundcube__database_map[roundcube__database].dbtype == 'mysql'
  tags: [ 'role::roundcube:database' ]

- name: Configure Roundcube
  template:
    src: 'srv/www/sites/config.inc.php.j2'
    dest: '{{ roundcube__git_checkout + "/config/config.inc.php" }}'
    owner: 'root'
    group: '{{ roundcube__group }}'
    mode: '0640'
  tags: [ 'role::roundcube:config' ]

- name: Update database schema
  command: 'php bin/updatedb.sh --package=roundcube --dir={{ roundcube__git_checkout }}/SQL'
  args:
    chdir: '{{ roundcube__git_checkout }}'
  become: True
  become_user: '{{ roundcube__user }}'
  register: roundcube__register_updatedb
  changed_when: roundcube__register_updatedb.stdout|d()
  when: (roundcube__register_version.stdout|d() and
         roundcube__git_version is version_compare(roundcube__register_version.stdout, '>')) or
        (roundcube__register_version_old is not skipped and
         roundcube__register_version_old.stdout|d())
  tags: [ 'role::roundcube:database' ]

- name: Post hooks
  include: '{{ lookup("task_src", "roundcube/post_main.yml") }}'
