---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'volkszaehler'
  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Setup and manage volkszaehler'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.5'

  platforms:

    - name: Debian
      versions:
        - jessie
        - stretch

    - name: Ubuntu
      versions:
        - trusty

  galaxy_tags:
    - smartmeter
    - smarthome
    - logging
    - web
