---

dependencies: []

galaxy_info:

  role_name: 'dokuwiki'
  author: 'Maciej Delmanowski'
  description: 'Install DokuWiki, a text-based wiki written in PHP5'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  galaxy_tags:
  - web
  - wiki
  - dokuwiki
  - php
