---

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened: '{{ fuse_base_packages }}'

- name: Divert original /etc/fuse.conf
  command: dpkg-divert --quiet --local --divert /etc/fuse.conf.dpkg-divert --rename /etc/fuse.conf
  args:
    creates: '/etc/fuse.conf.dpkg-divert'

- name: Setup udev rule for fuse to change file permissions
  template:
    src: 'etc/fuse.conf.j2'
    dest: '/etc/fuse.conf'

- name: Ensure fuse system group is present
  group:
    name: '{{ fuse_group }}'
    state: 'present'
    system: True

- name: Add fuse_users to fuse_group
  user:
    name: '{{ item }}'
    groups: '{{ fuse_group }}'
    append: True
  with_flattened:
    - '{{ fuse_users }}'
    - '{{ fuse_users_host_group }}'
    - '{{ fuse_users_host }}'

- name: Setup udev rule for fuse to change file permissions
  template:
    src: 'etc/udev/rules.d/fuse.rules.j2'
    dest: '/etc/udev/rules.d/99-fuse.rules'
  when: fuse_restrict_access | bool

- name: Ensure FUSE permissions are applied immediately
  file:
    path: '/dev/fuse'
    owner: 'root'
    group: '{{ fuse_group }}'
    mode: '{{ fuse_permissions }}'
  when: fuse_restrict_access | bool

- name: Remove udev rule for fuse
  file:
    path: '/etc/udev/rules.d/99-fuse.rules'
    state: 'absent'
  when: not (fuse_restrict_access | bool)
