---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'sysctl'
  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage kernel parameters using sysctl'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch

    - name: Ubuntu
      versions:
        - precise
        - trusty

  galaxy_tags:
    - security
    - hardening
    - linux
