---

dependencies: []

galaxy_info:

  role_name: 'golang'
  author: 'Nick Janetakis'
  description: 'Install Go language (golang) support using Debian packages'
  company: 'DebOps'
  license: 'GPLv3'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - development
    - programming
    - golang
    - go
