---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'fail2ban'
  author: 'Maciej Delmanowski'
  description: 'Install and configure fail2ban service'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - networking
    - security
    - firewall
    - ssh
