---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'etckeeper'
  company: 'DebOps'
  author: 'Robin Schneider, Maciej Delmanowski'
  description: 'Put /etc under version control using etckeeper'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.3'

  platforms:

    - name: Debian
      versions:
        - all

    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - versioning
    - etckeeper
    - etc
    - system
