---

dependencies: []

galaxy_info:

  role_name: 'icinga_db'
  author: 'Maciej Delmanowski'
  description: 'Manage Icinga 2 database'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - monitoring
    - icinga
    - nagios
