---

- name: Install and manage the caching HTTP proxy Apt-Cacher NG.
  hosts: [ 'debops_service_apt_cacher_ng' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ apt_cacher_ng__etc_services__dependent_list }}'

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ apt_cacher_ng__apt_preferences__dependent_list }}'
        - '{{ nginx_apt_preferences_dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ apt_cacher_ng__ferm__dependent_rules }}'
        - '{{ nginx_ferm_dependent_rules }}'

    - role: debops.nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx_servers:
        - '{{ apt_cacher_ng__nginx__servers }}'
      nginx_upstreams:
        - '{{ apt_cacher_ng__nginx__upstream }}'

    - role: debops.apt_cacher_ng
      tags: [ 'role::apt_cacher_ng', 'skip::apt_cacher_ng' ]
