---

- name: Put /etc under version control using etckeeper
  hosts: [ 'debops_all_hosts', 'debops_service_etckeeper' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.etckeeper
      tags: [ 'role::etckeeper', 'skip::etckeeper' ]
