---

- name: Configure GRUB
  hosts: [ 'debops_service_grub', 'debops_grub' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.grub
      tags: [ 'role::grub', 'skip::grub' ]
