---

- name: Install HashiCorp applications
  hosts: [ 'debops_service_hashicorp' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.hashicorp
      tags: [ 'role::hashicorp', 'skip::hashicorp' ]
