---

- name: Configure iSCSI Initiator
  hosts: [ 'debops_service_iscsi', 'debops_iscsi' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.unattended_upgrades
      tags: [ 'role::unattended_upgrades', 'skip::unattended_upgrades' ]
      unattended_upgrades__dependent_blacklist: '{{ iscsi__unattended_upgrades__dependent_blacklist }}'

    - role: debops.lvm
      tags: [ 'role::lvm', 'skip::lvm' ]

    - role: debops.iscsi
      tags: [ 'role::iscsi', 'skip::iscsi' ]
