---

- name: Manage LXC hosts
  hosts: [ 'debops_service_lxc' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ lxc__apt_preferences__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ lxc__ferm__dependent_rules }}'

    - role: debops.python
      tags: [ 'role::python', 'skip::python', 'role::lxc' ]
      python__dependent_packages3:
        - '{{ lxc__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ lxc__python__dependent_packages2 }}'

    - role: debops.lxc
      tags: [ 'role::lxc', 'skip::lxc' ]

# If a host has 'debops.dnsmasq' role configured, execute its playbook in case
# that configuration applied by the 'debops.lxc' role needs to be applied to
# 'dnsmasq' service. This should ensure that the '*.lxc' subdomain for internal
# LXC containers is resolvable on the LXC host.
#
# If the host is not in the Ansible inventory groups required by the
# 'dnsmasq.yml' playbook, this should not impact anything.
- import_playbook: 'dnsmasq.yml'
