---

- name: Manage MariaDB client
  hosts: [ 'debops_service_mariadb', 'debops_mariadb' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.mariadb
      tags: [ 'role::mariadb', 'skip::mariadb' ]
