---

- name: Configure Mosquitto service with Nginx
  hosts: [ 'debops_service_mosquitto_nginx' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ nginx__apt_preferences__dependent_list }}'

    - role: debops.etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ mosquitto__etc_services__dependent_list }}'

    - role: debops.tcpwrappers
      tags: [ 'role::tcpwrappers', 'skip::tcpwrappers' ]
      tcpwrappers__dependent_allow:
        - '{{ mosquitto__tcpwrappers__dependent_allow }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ mosquitto__ferm__dependent_rules }}'
        - '{{ nginx__ferm__dependent_rules }}'

    - role: debops.nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx__dependent_servers:
        - '{{ mosquitto__nginx__dependent_servers }}'
      nginx__dependent_upstreams:
        - '{{ mosquitto__nginx__dependent_upstreams }}'

    - role: debops.mosquitto
      tags: [ 'role::mosquitto', 'skip::mosquitto' ]
