---

- name: Manage local host and network database
  hosts: [ 'debops_all_hosts', 'debops_service_netbase' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.netbase
      tags: [ 'role::netbase', 'skip::netbase' ]
