---

- name: Manage NodeJS environment
  hosts: [ 'debops_service_nodejs', 'debops_nodejs' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ nodejs__apt_preferences__dependent_list }}'

    - role: debops.nodejs
      tags: [ 'role::nodejs', 'skip::nodejs' ]
