---

- name: Manage Network Time Protocol service
  hosts: [ 'debops_all_hosts', 'debops_service_ntp' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ ntp__ferm__dependent_rules }}'

    - role: debops.ntp
      tags: [ 'role::ntp', 'skip::ntp' ]
