---

- name: Manage OpenVZ Hardware Nodes
  hosts: [ 'debops_service_openvz', 'debops_openvz' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.openvz
      tags: [ 'role::openvz', 'skip::openvz' ]
