---

- name: Manage phpIPAM service
  hosts: [ 'debops_service_phpipam', 'debops_phpipam' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.phpipam
      tags: [ 'role::phpipam', 'skip::phpipam' ]
