---

- name: Manage PostgreSQL client
  hosts: [ 'debops_service_postgresql', 'debops_postgresql' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ postgresql__apt_preferences__dependent_list }}'

    - role: debops.postgresql
      tags: [ 'role::postgresql', 'skip::postgresql' ]
