---

- name: Manage SKS Keyserver
  hosts: [ 'debops_service_sks', 'debops_sks' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.sks
      tags: [ 'role::sks', 'skip::sks' ]
