---

- name: Configure swap files
  hosts: [ 'debops_service_swapfile' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.swapfile
      tags: [ 'role::swapfile', 'skip::swapfile' ]
