---

- name: Configure sysfs options
  hosts: [ 'debops_service_sysfs' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.sysfs/env
      tags: [ 'role::sysfs', 'role::secret' ]

    - role: debops.secret
      tags: [ 'role::secret', 'role::sysfs' ]
      secret__directories:
        - '{{ sysfs__secret__directories | d([]) }}'

    - role: debops.sysfs
      tags: [ 'role::sysfs', 'skip::sysfs' ]
