---

# - name: Ensure specified packages are in there desired state
#   package:
#     name: '{{ item }}'
#     state: '{{ "present" if (tor__deploy_state == "present") else "absent" }}'
#   with_flattened: '{{ tor__base_packages }}'
#   tags: [ 'role::tor:pkgs' ]
