---

dependencies:

  - role: debops.secret

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'owncloud'
  company: 'DebOps'
  author: 'Maciej Delmanowski, Hartmut Goebel, Robin Schneider'
  description: 'Install and manage ownCloud instance'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.4'

  platforms:

    - name: Debian
      versions:
        - jessie

        ## Main target, used in production.
        - stretch

    - name: Ubuntu
      versions:
        ## CI testing target
        - trusty

  galaxy_tags:
    - cloud
    - private
    - privacy
    - sharing
    - files
    - calender
    - contacts
    - web
    - owncloud
    - nextcloud
