---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Ondřej Surý APT repositories [[[

- name: Add Ondrej Sury APT key
  apt_key:
    id: '{{ php__sury_apt_key_id }}'
    state: 'present'
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver)
                   else "hkp://pool.sks-keyservers.net" }}'
  when: php__sury|bool

- name: Add Ondrej Sury repository
  apt_repository:
    repo: '{{ php__sury_apt_repo }}'
    state: 'present'
    update_cache: True
  when: php__sury|bool

                                                                   # ]]]
# PHP version and Ansible variables [[[

- name: Reset PHP Ansible local facts
  file:
    path: '/etc/ansible/facts.d/php.fact'
    state: 'absent'
  register: php__register_local_facts_reset
  when: php__reset|bool

- name: Gather facts on reset
  action: setup
  when: php__register_local_facts_reset is changed

- name: Detect PHP version from available packages
  environment:
    LC_ALL: 'C'
  shell: apt-cache show {{ php__version_preference | join(' ') }} | grep -E '^Package:\s+php[0-9.]+$' | head -n 1 | awk '{print $2}' | sed -e 's/^php//'
  register: php__register_version
  check_mode: False
  changed_when: False
  tags: [ 'role::php:pools', 'role::php:config' ]

- name: Detect PHP long version from available packages
  environment:
    LC_ALL: 'C'
  shell: apt-cache policy {{ php__version_preference | join(' ') }} | grep -E '^\s+Candidate:\s+' | grep --invert-match 'none' | head -n 1 | sed --regexp-extended 's/\s*[[:alnum:]]+:\s* ([^+-]+).*/\1/g;'
  register: php__register_long_version
  check_mode: False
  changed_when: False
  tags: [ 'role::php:pools', 'role::php:config' ]

- name: Set PHP version
  set_fact:
    php__version: '{{ ansible_local.php.version
                      if (ansible_local|d() and ansible_local.php|d() and
                          ansible_local.php.version|d())
                      else php__register_version.stdout }}'
    php__long_version: '{{ ansible_local.php.long_version
                           if (ansible_local|d() and ansible_local.php|d() and
                               ansible_local.php.long_version|d() and
                               ansible_local.php.long_version|d() != "(none)")
                           else php__register_long_version.stdout }}'
  tags: [ 'role::php:pools', 'role::php:config' ]

- name: Set PHP base paths
  set_fact:
    php__etc_base: '{{ ("/etc/php/" + php__version)
                       if (php__version is version_compare("7.0", ">=") or php__sury|bool)
                       else "/etc/php5" }}'
    php__lib_base: '{{ ("/usr/lib/php/" + php__version)
                       if (php__version is version_compare("7.0", ">=") or php__sury|bool)
                       else "/usr/lib/php5" }}'
    php__run_base: '{{ "/run/php"
                       if (php__version is version_compare("7.0", ">=") or php__sury|bool)
                       else "/run" }}'
    php__logrotate_lib_base: '{{ "/usr/lib/php"
                                 if (php__version is version_compare("7.0", ">=") or php__sury|bool)
                                 else "/usr/lib/php5" }}'
  tags: [ 'role::php:pools', 'role::php:config' ]

                                                                   # ]]]
